name: Build image for node web service with React

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Build Docker and publish
              uses: docker/build-push-action@1
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
                repository: zhanchengdev/twitter-web
                tag_with_ref: true
                tag_with_sha: true